# Generated by Django 3.1 on 2022-06-17 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20220617_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 13, 18, 25, 427840)),
        ),
    ]
